version : "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: MINEME_PROD
    environment:
      TZ: Asia/Seoul
    env_file:
     - ./.env
    ports:
        - ${PROD_PORT}:${SERVER_PORT}
    volumes:
        - ./build/libs:/app
    restart: always

  dev:
    build:
      context: .
      dockerfile: Dockerfile_dev
    container_name: MINEME_DEV
    environment:
      TZ: Asia/Seoul
    env_file:
     - ./.env
    ports:
        - ${DEV_PORT}:${SERVER_PORT}
    volumes:
        - ./build/libs:/app
    restart: always

  nginx:
    image: nginx
    container_name: MINEME_NGINX
    env_file:
     - ./.env
    ports:
        - 8000:${PROD_PORT}
    volumes:
        - ./app:/app
    working_dir: /app
    depends_on:
      - app
      - dev
    restart: always
