spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mineme
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MariaDB10Dialect
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: true
