name: MINEME-DEV CI/CD

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Make Application.yml
        run: |
          ## create application.yml
          cd ./src/main/resources

          # GitHub-Actions 에서 설정한 값을 application.yml 파일에 쓰기
          echo "${{ secrets.APPLICATION }}" > ./application.yml
        shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Docker build
        run: |
          DATE=$(date "+%y.%m.%d")
          docker build -t ${{ secrets.DOCKER_REPO }}/mineme-api:$DATE .
      
      - name: Docker push
        run: |
          DATE=$(date "+%y.%m.%d")
          docker push ${{ secrets.DOCKER_REPO }}/mineme-api:$DATE

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            DATE=$(date "+%y.%m.%d")
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker stop MINEME_DEV
            docker rm -f MINEME_DEV
            docker pull ${{ secrets.DOCKER_REPO }}/mineme-api:$DATE
            docker-compose up -d dev
            docker image prune -f
      